apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nextcloud
  name: nextcloud
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nextcloud
  type: LoadBalancer
status:
  loadBalancer: {}
